---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/alex1989hu/kubelet-serving-cert-approver
  ref:
    tag: v0.8.4
  ignore: |
    /*
    !/deploy
