---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kubelet-serving-cert-approver
  namespace: flux-system
spec:
  targetNamespace: *app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: deploy/standalone
  prune: true
  sourceRef:
    kind: GitRepository
    name: *app
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  images:
    - name: ghcr.io/alex1989hu/kubelet-serving-cert-approver
      newTag: 0.8.4
